apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
        - name: auth-backend
          image: nginx:1.13-alpine
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static-files
              mountPath: /static
            - name: media-files
              mountPath: /media
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: certs
              mountPath: /certs
      volumes:
        - name: static-files
          hostPath:
            path: /mnt/data/microservices/auth-gatway-backend/static  # Change path if needed
        - name: media-files
          hostPath:
            path: /mnt/data/microservices/auth-gatway-backend/media  # Change path if needed
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: certs
          hostPath:
            path: /mnt/data/docker_config/certs  # Change path if needed
