apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth_portal
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth_portal
  template:
    metadata:
      labels:
        app: auth_portal
    spec:
      containers:
        - name: auth_portal
          image: rahulpatil1992/auth_portal:latest
          ports:
            - containerPort: 8002


