apiVersion: v1
kind: Service
metadata:
  name: auth-portal-service
  namespace: my-app
spec:
  selector:
    app: auth-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: NodePort
