apiVersion: v1
kind: Service
metadata:
  name: auth_portal-service
  namespace: my-app
spec:
  selector:
    app: auth_portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP
