apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth_service
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth_service
  template:
    metadata:
      labels:
        app: auth_service
    spec:
      containers:
        - name: auth_service
          image: rahulpatil1992/auth_service:latest
          ports:
            - containerPort: 5000
