apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rahulpatil1992/auth_service:latest
          ports:
            - containerPort: 8001
