apiVersion: v1
kind: Service
metadata:
  name: auth_service-service
  namespace: my-app
spec:
  selector:
    app: auth_service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

