apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  namespace: my-app
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP

