apiVersion: v1
data:
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGKTCCBRGgAwIBAgIRAPbZlEQKOqkT08xH7tKTxlAwDQYJKoZIhvcNAQELBQAw
    gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
    BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE
    AxMuU2VjdGlnbyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD
    QTAeFw0yNDA1MjIwMDAwMDBaFw0yNTA2MjIyMzU5NTlaMBUxEzARBgNVBAMMCiou
    ZG9xZnkuaW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD3HL9V6PbH
    7sFp/SzXlTn9XY8dnoYz0hK9ZfMTEouABdNwbhCqc6NfKK0Yasnh8yuTHkHxGSn/
    V5sPKs0QUeiW+UkdGp5/LdK7vm/tsSF7chvPz4KYAhmW45kup3lkeSZrt4pk70N5
    /RefQ59eORkPZTWxFaXKNx8e033MV9owGwYP1Hua+YhntnH44bizaGbUcvx1r3iD
    QP0UelCVMs6Tuq9mgcxdrg9ffrJE5VSraMnAZ+gZjPalna5tKwu3aZ+HnIO0FMtW
    IvFZn5eMG9T3ZIt/1j/RffvWC2KZx1ZVO8Gag4vk81zHPr/qA2biIcwPbMpA2WpJ
    zci5MSt9phu3AgMBAAGjggL3MIIC8zAfBgNVHSMEGDAWgBSNjF7EVK2K4Xfpm/mb
    BeG4AY1h4TAdBgNVHQ4EFgQUDVjR/ix1rbkXuqyjH2TjOax9PW4wDgYDVR0PAQH/
    BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
    BwMCMEkGA1UdIARCMEAwNAYLKwYBBAGyMQECAgcwJTAjBggrBgEFBQcCARYXaHR0
    cHM6Ly9zZWN0aWdvLmNvbS9DUFMwCAYGZ4EMAQIBMIGEBggrBgEFBQcBAQR4MHYw
    TwYIKwYBBQUHMAKGQ2h0dHA6Ly9jcnQuc2VjdGlnby5jb20vU2VjdGlnb1JTQURv
    bWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5jcnQwIwYIKwYBBQUHMAGGF2h0
    dHA6Ly9vY3NwLnNlY3RpZ28uY29tMB8GA1UdEQQYMBaCCiouZG9xZnkuaW6CCGRv
    cWZ5LmluMIIBfwYKKwYBBAHWeQIEAgSCAW8EggFrAWkAdwDPEVbu1S58r/OHW9lp
    LpvpGnFnSrAX7KwB0lt3zsw7CAAAAY+eoEahAAAEAwBIMEYCIQClErAi7qCKX4tL
    sj//Z/Oyg03SmNb+2RGTx2Tg4It60QIhALBxChC8UuP4I6Hpf5TFpHDPkQITeZy+
    td09Ak4NA8SyAHYAouMK5EXvva2bfjjtR2d3U9eCW4SU1yteGyzEuVCkR+cAAAGP
    nqBGVQAABAMARzBFAiAvqODTKSoHGH9mZNbDQT4qS1QXRJ4x3z8lYXEajXMpWwIh
    AKgTbAhnxpJMkLDhNFyT3fve6Svc/L59wyzP3svrUmpPAHYATnWjJ1yaEMM4W2zU
    3z9S6x3w4I4bjWnAsfpksWKaOd8AAAGPnqBGSwAABAMARzBFAiAU1gYDJ74ojoOQ
    DRgeh9ptvmwXHtVHqm8HCRTkwo8dtwIhAK6DBg19A7vauYx97pd6F57HyFIeV4JS
    ytBBbQUDJs4PMA0GCSqGSIb3DQEBCwUAA4IBAQAqBeWP9tLvak+ayWNCOv/POKqA
    lNHM87JsUroheCeAlEbDtVU35wirfnWotmp7nt+XRqkg8MXw/vjcsSiW+viFSel5
    r7cVvavrkR6N13TvUud1hKU8Mp6hIn5pIEmoYTbVe3mwUUhMTQ1zAPpt8vI29zNB
    PMt7YBUFE5B3EOsgBF01gmcvSca3AGTzkreRBGRKtTRkrhvBFmChF22oTdEgA52r
    6+TBlWjO5zOcbsHSqieg6/xVvL23tRQvFEveUHSEi6WQ5qhKcdlbQZCtT08rEloI
    orwRQLEOP/jRMTQUH+XKg70vz4jIjEOeL6bUNq8eplO0yA2iMwGH/MIpBw+H
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
    iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
    cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
    BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
    MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
    BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
    ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
    VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
    TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
    eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
    oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
    Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
    uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
    BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
    +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
    CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
    LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
    BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
    bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
    L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
    ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
    7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
    H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
    RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
    xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
    sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
    l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
    6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
    LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
    yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
    00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----
    MIIFgTCCBGmgAwIBAgIQOXJEOvkit1HX02wQ3TE1lTANBgkqhkiG9w0BAQwFADB7
    MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD
    VQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UE
    AwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4
    MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5
    MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO
    ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0
    aG9yaXR5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sI
    s9CsVw127c0n00ytUINh4qogTQktZAnczomfzD2p7PbPwdzx07HWezcoEStH2jnG
    vDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR1GJk23+jBvGIGGqQ
    Ijy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bIcmfb
    IWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0
    tyA9yn8iNK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97E
    xwzf4TKuzJM7UXiVZ4vuPVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNV
    icQNwZNUMBkTrNN9N6frXTpsNVzbQdcS2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5
    D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e5XOsIzstAL81VXQJSdhJ
    WBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10Yy+xUGUJ
    5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzG
    KAgEJTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB8jCB7zAfBgNVHSMEGDAWgBSg
    EQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rID
    ZsswDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAG
    BgRVHSAAMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwuY29tb2RvY2EuY29t
    L0FBQUNlcnRpZmljYXRlU2VydmljZXMuY3JsMDQGCCsGAQUFBwEBBCgwJjAkBggr
    BgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMA0GCSqGSIb3DQEBDAUA
    A4IBAQAYh1HcdCE9nIrgJ7cz0C7M7PDmy14R3iJvm3WOnnL+5Nb+qh+cli3vA0p+
    rvSNb3I8QzvAP+u431yqqcau8vzY7qN7Q/aGNnwU4M309z/+3ri0ivCRlv79Q2R+
    /czSAaF9ffgZGclCKxO/WIu6pKJmBHaIkU4MiRTOok3JMrO66BQavHHxW/BBC5gA
    CiIDEOUMsfnNkjcZ7Tvx5Dq2+UUTJnWvu6rvP3t3O9LEApE9GQDTF1w52z97GA1F
    zZOFli9d31kWTz9RvdVFGD/tSo7oBmF0Ixa1DVBzJ0RHfxBdiSprhTEUxOipakyA
    vGp4z7h/jnZymQyd/teRCBaho1+V
    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----
    MIIEMjCCAxqgAwIBAgIBATANBgkqhkiG9w0BAQUFADB7MQswCQYDVQQGEwJHQjEb
    MBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHDAdTYWxmb3JkMRow
    GAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UEAwwYQUFBIENlcnRpZmlj
    YXRlIFNlcnZpY2VzMB4XDTA0MDEwMTAwMDAwMFoXDTI4MTIzMTIzNTk1OVowezEL
    MAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE
    BwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNVBAMM
    GEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAL5AnfRu4ep2hxxNRUSOvkbIgwadwSr+GB+O5AL686tdUIoWMQua
    BtDFcCLNSS1UY8y2bmhGC1Pqy0wkwLxyTurxFa70VJoSCsN6sjNg4tqJVfMiWPPe
    3M/vg4aijJRPn2jymJBGhCfHdr/jzDUsi14HZGWCwEiwqJH5YZ92IFCokcdmtet4
    YgNW8IoaE+oxox6gmf049vYnMlhvB/VruPsUK6+3qszWY19zjNoFmag4qMsXeDZR
    rOme9Hg6jc8P2ULimAyrL58OAd7vn5lJ8S3frHRNG5i1R8XlKdH5kBjHYpy+g8cm
    ez6KJcfA3Z3mNWgQIJ2P2N7Sw4ScDV7oL8kCAwEAAaOBwDCBvTAdBgNVHQ4EFgQU
    oBEKIz6W8Qfs4q8p74Klf9AwpLQwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF
    MAMBAf8wewYDVR0fBHQwcjA4oDagNIYyaHR0cDovL2NybC5jb21vZG9jYS5jb20v
    QUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNqA0oDKGMGh0dHA6Ly9jcmwuY29t
    b2RvLm5ldC9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNybDANBgkqhkiG9w0BAQUF
    AAOCAQEACFb8AvCb6P+k+tZ7xkSAzk/ExfYAWMymtrwUSWgEdujm7l3sAg9g1o1Q
    GE8mTgHj5rCl7r+8dFRBv/38ErjHT1r0iWAFf2C3BUrz9vHCv8S5dIa2LX1rzNLz
    Rt0vxuBqw8M0Ayx9lt1awg6nCpnBBYurDC/zXDrPbDdVCYfeU0BsWO/8tqtlbgT2
    G9w84FoVxp7Z8VlIMCFlA2zs6SFz7JsDoeA3raAVGI/6ugLOpyypEBMs1OUIJqsi
    l2D4kF501KKaU73yqWjgom7C12yxow+ev+to51byrvLjKzg6CYG1a4XXvi3tPxq3
    smPi9WIsgtRqAEFQ8TmDn5XpNpaYbg==
    -----END CERTIFICATE-----
  server.csr: ""
  server.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD3HL9V6PbH7sFp
    /SzXlTn9XY8dnoYz0hK9ZfMTEouABdNwbhCqc6NfKK0Yasnh8yuTHkHxGSn/V5sP
    Ks0QUeiW+UkdGp5/LdK7vm/tsSF7chvPz4KYAhmW45kup3lkeSZrt4pk70N5/Ref
    Q59eORkPZTWxFaXKNx8e033MV9owGwYP1Hua+YhntnH44bizaGbUcvx1r3iDQP0U
    elCVMs6Tuq9mgcxdrg9ffrJE5VSraMnAZ+gZjPalna5tKwu3aZ+HnIO0FMtWIvFZ
    n5eMG9T3ZIt/1j/RffvWC2KZx1ZVO8Gag4vk81zHPr/qA2biIcwPbMpA2WpJzci5
    MSt9phu3AgMBAAECggEAZD+SU6zl6KgwaOoftfnBA8tf0vlLolw35AQm/3bHhxFV
    /Md6FVxCS8l5p20zJ2n6JH3i7Idz5TXKHvYTKOrBu/W3tonlAN07H5UbXUc9uRHK
    vJyHc1luvirpKucgNSV887gK+fWi3ytQ2Pia/6OUSg2aIZQRpR6FjoDoCO0fA+I2
    k1RlwG8o2Vx30yKqSjyHGn2uQbbsy+v6dil9jzvDA1R477/2n1TsAToXC2Pq4xIr
    yvKNJgk96DUln9B3ihtrwbyVlQR8HZbBQL/5K73c8Eglvhfbc6f2udCcCpobGfs3
    4L+S+HW8wnU+7UvLleLzuI8E6rh7CWHapU+GAMhteQKBgQD/bCtWhUrVsuVmJmBH
    9nryZEQdqLsoWcAuFvAIG4hV7hlD6lygM3DYfFXt4wG6V3T9HPw5HqfcbgPPMWDu
    1gDejZmZMOaZDE0iIRz3RtTQm0Ad25emN2DYF+y2SzFQqntCUExcunfpYXzFSRk6
    5CvodoNHtFWo/UHQ/wjxZgnqqwKBgQD3q8S2E4bDzU8iEYzRRuZf2gs3qSIy68jx
    jmpAOd9K1Rr2EdNJMWDgSOfPENCy63+51Q25n7J3HHd4VNBUYAwPGldst2f/I8Op
    J0NRU71PO1iMbptFibZIDguDYfehvSPKWLFgQMkHEm4qoePRaFzh0hmSejTg6Vyk
    XBeTZWWTJQKBgEVHobmmDdZI39AFOLhMMqzsZU1mJt2a+nWF4zVPwnsMSe4R823A
    hisyDlyn5iAU+LZu1jroBb/UV1QroI8nnLTA05ipmuKIY6OON70aiT7L3Wg717ZN
    7wat9pa7bnTiyOwDu7KrITs8Jguc+CrxGLfE7XbVgyaDCwcVJefUNXxhAoGAfTWN
    YS9F9j8ZPnP46OQbG2I0QZN0AqJJGDWTaZzYUhCibLxeQKaB/2FcL8ake4+rJtua
    8LjXlHgDvgXCvKVB83CxufiOzuHZzO5Yjgjzr9ak0XopbWJNkOfo0ib49f+U1Hs6
    URrvhm++2ja14ewM6O06mF7H1NylRUJ5eL7ONzECgYEA0OMdCF4Y6A5LDw4HRCAJ
    nKEQ9bICx2kbSU8zHG+IOpwbNXOpWmstleJE2EN3jAFqmqfVGa7mVkuCIExMt5gY
    /GVgVymgSNWJVPOtOa6C8r7/LPm7xjSWAFnGUqBoQDy1yKLM/ek1Z3OgLEulESyp
    vD4e/glWJGn19X5I2aFDwJw=
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: auth-backend
  name: auth-backend-cm3
