apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: auth-service-claim2
  name: auth-service-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
