apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth-backend
  name: auth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: auth-backend
    spec:
      containers:
        - image: nginx:1.13-alpine
          name: auth-backend
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: auth-backend-cm2
              readOnly: true
              subPath: nginx.conf
            - mountPath: /certs
              name: auth-backend-cm3
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: auth-backend-cm2
          name: auth-backend-cm2
        - configMap:
            name: auth-backend-cm3
          name: auth-backend-cm3
