apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - |
              echo "Starting django server ..."
              /deploy_commands.sh
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  key: API_URL
                  name: env
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: env
          image: rahulpatil1992/auth_service:latest
          name: auth-service
          volumeMounts:
            - mountPath: /deploy_commands.sh
              name: auth-service-cm1
              subPath: deploy_commands.sh
            - mountPath: /logs
              name: auth-service-claim2
          workingDir: /home/python/app
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: deploy_commands.sh
                path: deploy_commands.sh
            name: auth-service-cm1
          name: auth-service-cm1
        - name: auth-service-claim2
          persistentVolumeClaim:
            claimName: auth-service-claim2
