apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth-portal
  name: auth-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-portal
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: auth-portal
    spec:
      containers:
        - env:
            - name: API_URL
          image: rahulpatil1992/auth_portal:latest
          name: auth-portal
          ports:
            - containerPort: 8002
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: auth-portal-cm1
              readOnly: true
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: auth-portal-cm1
          name: auth-portal-cm1
