apiVersion: v1
data:
  nginx.conf: |
    # nginx_config/default.conf

    events {
        worker_connections 1024;
    }

    http {
        client_max_body_size 50M;

        upstream auth_portal {
            server auth_portal:8002;
        }

        upstream auth_service {
            server auth_backend:8000;
        }

        server {
            listen 80 default_server;
            server_name _;
            return 301 https://$host$request_uri;
        }

        server {
            listen 443;
            server_name www.beta2-auth-gateway.doqfy.in beta2-auth-gateway.doqfy.in;

            ssl on;
            ssl_certificate /certs/server.crt;
            ssl_certificate_key /certs/server.key;

            location / {
                proxy_pass http://auth_portal;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }

        server {
            listen 443;
            server_name www.beta2-auth-gateway-api.doqfy.in beta2-auth-gateway-api.doqfy.in;

            ssl on;
            ssl_certificate /certs/server.crt;
            ssl_certificate_key /certs/server.key;

            location / {
                proxy_pass http://auth_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }


    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy-cm0
